try to debug az login (#47)
* try to debug az login

* add retry for az login

* add tflint override config to bypass failed tflint check

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -39,11 +39,22 @@ jobs:
       fail-fast: false
     steps:
       - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
-
       - name: Test example
         shell: bash
         run: |
           set -e
+          MAX_RETRIES=10
+          RETRY_COUNT=0
+          until [ $RETRY_COUNT -ge $MAX_RETRIES ]
+          do
+            az login --identity --username $MSI_ID > /dev/null && break
+            RETRY_COUNT=$[$RETRY_COUNT+1]
+            sleep 10
+          done
+          if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
+            echo "Failed to login after $MAX_RETRIES attempts."
+            exit 1
+          fi
           az login --identity --username $MSI_ID > /dev/null
           export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
           export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
